### PR TITLE
IAE-54007: Add icon package, update components to use

### PR DESCRIPTION
**Pull request by cwolf10**
## Description
Added ngx-uswds-icons to package. Updated SDS to use ngx-uswds-icons' IconComponent rather than SDS'. 

## Motivation and Context
IAEDEV-54007

## Type of Change (Select One and Apply Github Label)

- [ ] Bug fix (non-breaking change which fixes an issue) -> Apply bugfix label
- [x] New feature (non-breaking change which adds functionality) -> Apply enhancement label
- [ ] Breaking change (fix or feature that would cause existing functionality to change) -> Apply breaking label

## Which browsers have you tested?
- [ ] Internet Explorer 11
- [ ] Edge
- [x] Chrome
- [x] Firefox
- [x] Safari

## Checklist:

- [ ] I have read the (https://github.comv/GSA/sam-ui-elements/blob/CONTRIBUTING.md)[CONTRIBUTING.md] document.
- [ ] My code passes the automated linter.
- [ ] This code has been reviewed by another team member and passes the reviewer checklist found in (https://github.comv/GSA/sam-ui-elements/blob/CONTRIBUTING.md)[CONTRIBUTING.md]
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] My code is 508 compliant as tested by AMP and JAWS
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Bibek-Regmi** [comment]
Is this planned to be released with 10.0.35 or are we waiting until MFE teams update over to usa-icon?

**Comment by cwolf10** [comment]
This will be included in next release. It does not force dev teams to do the work to use usa-icon at this time. Just updates SDS components to use the new library.

**Review by Bibek-Regmi — DISMISSED** [review]

**Comment by Bibek-Regmi** [comment]
Approved - during release, we should make sure teams know that they need to add ngx-uswds-icons to their dependency

**Comment by cwolf10** [comment]
Good point, I will be sure to include it in the messaging with the release notes.

**Review by Bibek-Regmi — APPROVED** [review]

**Pull request merged**
