### PR TITLE
Delete functionality

### LINKED ISSUE #1482: Table Delete Functionality

### LINKED ISSUE #1484: SDS Table component enhancement
**Is your feature request related to a problem? Please describe.**

   According to the new mockup request, adding the multiple checkboxes and dropdown  in a data table results is not possible with SDS Table.  We are requesting to enhance the SDS Table component in order to satisfy the below requirement.

Please refer the below enabler request.
IAEMOD-29743

### PR DESCRIPTION
**Pull request by cwolf10**
## Description

Add input `isClickable` to SdsTableColumnDefComponent to limit which columns can trigger rowClicked event. By default, rowClicked event behavior will not change if isClickable is not set true on any column.
Add [demo](https://gsa.github.io/sam-design-system/pr-preview/pr-1498/?path=/story/components-table--select-row) that utilizes isClickable input and provides additional example of the templating that is supported by sds-table and associated components.

## Motivation and Context
Resolves #1484 
Resolves #1482 

## Type of Change (Select One and Apply Github Label)

- [ ] Bug fix (non-breaking change which fixes an issue) -> Apply bugfix label
- [x] New feature (non-breaking change which adds functionality) -> Apply enhancement label
- [ ] Breaking change (fix or feature that would cause existing functionality to change) -> Apply breaking label

## Which browsers have you tested?
- [ ] Internet Explorer 11
- [ ] Edge
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

## Checklist:

- [ ] I have read the (https://github.comv/GSA/sam-ui-elements/blob/CONTRIBUTING.md)[CONTRIBUTING.md] document.
- [ ] My code passes the automated linter.
- [ ] This code has been reviewed by another team member and passes the reviewer checklist found in (https://github.comv/GSA/sam-ui-elements/blob/CONTRIBUTING.md)[CONTRIBUTING.md]
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] My code is 508 compliant as tested by AMP and JAWS
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by shayan-roshan** [comment]
can you resolve the conflicts?

**Comment by cwolf10** [comment]
@shayan-roshan Done.

**Review by yerramshilpa — CHANGES_REQUESTED** [review]
@cwolf10 Looks good to me, can you resolve the conflicts?

**Comment by cwolf10** [comment]
@yerramshilpa Resolved

**Review by yerramshilpa — APPROVED** [review]

**Pull request merged**
